---
# tasks file for webserver

- name: install nginx
  apt:
    name: nginx
    state: present

- name: Copy file index.html
  copy: src=index.html dest={{ dest_folder }}/index.html mode=555
  notify:
    - restart nginx
